### ISSUE TITLE
make help message clearer

### ISSUE THREAD

**Issue by sadlittletree** [Beatso/Picasso#22]
Picasso says "mention me" twice, it should say "Mention me in a message with an image, or in a reply to an image to scale it."
<img width="1440" alt="Captura de Pantalla 2021-05-19 a la(s) 6 32 38 p m" src="https://user-images.githubusercontent.com/81985011/118897928-f77ffa80-b8d0-11eb-9541-76a7f45971ea.png">

**Comment by Beatso** [comment]
This isn't a mistake, but I guess it's more clear with just one "mention me". I'll change this soon!

**Comment by Beatso** [comment]
help message will be rewritten in #27
